---
language: ruby
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
- 1.9.2
- 1.8.7
- jruby-18mode
- jruby-19mode
- rbx
- ruby-head
- jruby-head
- ree
matrix:
  allow_failures:
  - rvm: 1.8.7
  - rvm: ree
  - rvm: jruby-18mode
  - rvm: jruby-19mode
  - rvm: jruby-head
  fast_finish: true
env:
  global:
  - JRUBY_OPTS=-Xcext.enabled=true
  - secure: ! 'AuTqK4GVSvHxsUdgDXivtFuCQjB7EX19zM5C2b2omp1BLAQsnAyDse/6x2Oe

      kB7SzCwH/PIeSJ8xNzcKF/c32lJZBdQAU7Cz210XoXCevefpWa4Y/4u/nNi2

      eltSdGuJWwAiFMjBGz4IHa2Q7UnS9FcyB4FZXfaPCVZdkmffSzg='
  - secure: ! 'Ajl+5EjsPtpEh25qfyk0RF2i/oM6g29AWqRHmC+I/TuWhMaFawdTESiqbvJk

      Pir0ogqE+GufgueOYHKmIoYUHfs+dwS82/zBt3bmd8hpSsIGYGMcKVT8Zswe

      QKT3JOOv7Igf96sgHhDk9T/n8ZlyUhtAJmau2MGdYw6Un0gTnZQ='
  - secure: ! '1GFCEhzcB7bPhWQA2BJTerMvTa0tZjyrnozP5jgz5ejX5pKp8Q6OQogrrPk9

      HZ1KuobWBKF2mnT8S0Kmjia5oR7XQGwanV12Xpe2e+NnqrbWsf7ZZ9OcUK6D

      MjxAZ2zKo0l6zGyor8Alf5ejcAzTJky+/I855tn8zA8jNPG9fD4='
  - secure: ! 'xUpzXMelLHrVpjT64uuWi8TbDAElda+gBPXLctHwrL+IgxHekAz6cDIgyukT

      bGlWHFpl0lpedv9/eZbv7OchQOcWg45TccbxMcMjHfxYSDNr73RI1L0epn6j

      UsvChSvlzCmUoYeXqygr/1t1ujABLqoaT+YThn957hlVIoUMOUA='
